### ISSUE TITLE
Dokumentation does not fit to the current version of solarium

### ISSUE THREAD

**Issue by B0rner** [Sammaye/yii2-solr#10]
The current version of solarium requires an different connection-setting which doesn't fits to your documentation:
https://github.com/solariumphp/solarium#pitfall-when-upgrading-from-earlier-versions-to-5x

**Comment by Sammaye** [comment]
I haven't really used this in nearly 4 years now.

If you have the fix you can make a PR and I will merge, otherwise I haven't even got a dev environment with Yii installed
