### ISSUE TITLE
Little "tutorial" about how use this extension

### ISSUE THREAD

**Issue by davidoff77vt** [Sammaye/yii2-solr#2]
Would be usefull at least for me a short tutorial about how configure this extension

**Comment by Sammaye** [comment]
I do provide a short one in the readme since the extension is a very thin layer, however, what else would you like to see?

**Comment by davidoff77vt** [comment]
my problem is that i dont know how exactly configure this extension to reach my solr instance
(i know this is not an issue but was the only way i saw to contact u)

**Comment by Sammaye** [comment]
Anything that blocks usage of this extesnion that is to do with me belongs here :). I will write something up in a short bit

**Comment by davidoff77vt** [comment]
Well i really should sleep more and code less... in the client file is the field $option and when i define the component i just need to put there the parameters as i would do with solarium... 

do i am right?

**Comment by Sammaye** [comment]
Indeed, so here is an actual example:
```php
	'components.solr' => [
		'class' => 'common\components\solr\Client',
		'options' => [
			'endpoint' => [
				'solr1' => [
					'host' => '104.xx.xxx.xxx',
					'port' => '8983',
					'path' => '/solr'
				]
			]
		]
	],
```

**Comment by davidoff77vt** [comment]
yes now i got it :)
Thanks

**Comment by Sammaye** [comment]
Done: https://github.com/Sammaye/yii2-solr/commit/dddd17e3ec41a034693c73dc9db6bf8947265222 thanks
