### ISSUE TITLE
Hi Sam

### ISSUE THREAD

**Issue by nenad-zivkovic** [Sammaye/yii2-solr#3]
I have sent you an email on address found here https://sammaye.wordpress.com/notes-on-my-code/

Sorry because I had to open new issue, but I do not have any other way of contacting you :D

**Comment by Sammaye** [comment]
That's fine, what's up?

**Comment by nenad-zivkovic** [comment]
I will paste some content of email here: 

I need to build yii2 search built on top of solr, and I have never done it before so I need to ask you, can I do it with your extension ? Do I need to have Solarium installed or something ?

Also I do not understand this query: $query->setQuery('edismax&qf=title^20.0 OR description^0.3');

What is this doing ? I was trying to read Solarium docs but I couldn't find any good explanation.

Also is there anything else needed to make search happen except:

$query = Yii::$app->solr->createSelect();
$query->setQuery('edismax&qf=title^20.0 OR description^0.3');
$result = Yii::$app->solr->select($query);
var_dump($result->getNumFound());

Where do you put this code, do you need to write any normal AR query or something ?

**Comment by Sammaye** [comment]
> I have few questions about your https://github.com/Sammaye/yii2-solr 
> extension.
>
> I need to build yii2 search built on top of solr, and I have never done 
> it before so I need to ask you, can I do it with your extension ? Do I 
> need to have Solarium installed or something ?

This extension will install Solarium when you install it through composer so you shouldn't need to worry about that, but yes, it requires Solarium. It is basically a Yii2 compatibility layer for Solarium.
 
> Also I do not understand this query: 
> $query->setQuery('edismax&qf=title^20.0 OR description^0.3');
>
> What is this doing ? I was trying to read Solarium docs but I couldn't 
> find any good explanation.
 
This is basically setting the query part of your Solr request. It is a straight 1-to-1 to the query you normally would run in the Solr control panel or via its REST API.

This is the doc page reference within Solr itself: https://wiki.apache.org/solr/ExtendedDisMax#Overview

> Also is there anything else needed to make search happen except:
>
> $query = Yii::$app->solr->createSelect();
> $query->setQuery('edismax&qf=title^20.0 OR description^0.3');
> $result = Yii::$app->solr->select($query);
> var_dump($result->getNumFound());
>
> Where do you put this code, do you need to write any normal AR query or 
> something ?

That is indeed enough. You can put it anywhere, within the controller action or the view. It will run all the same.

**Comment by nenad-zivkovic** [comment]
This is amazing, you made my life much easier now.

But one more question just to be sure. If I have controller DataController with action called actionSearch(),  I will point my html search box to this actionSearch() and put this code inside of it ?

    $query = Yii::$app->solr->createSelect();
    $query->setQuery('edismax&qf=title^20.0 OR description^0.3');
    $result = Yii::$app->solr->select($query);

Does this actionSearch need to accept any parameters ?

Thanks :D

**Comment by nenad-zivkovic** [comment]
Now I see in your README that you have these classes:

    common\components\solr\Client

    common\models\SolrResult

Are they custom made ? Can you provide examples of code inside, what do we need there ?

**Comment by Sammaye** [comment]
> But two more questions just to be sure. If I have controller DataController with action called actionSearch(), I will point my html search box to this actionSearch() and put this code inside of it ?

That involves quite a bit of code but I will try and outline it here.

You probably want to make a new controller function of:
````php
public function actionSearch()
{
    $query = Yii::$app->solr->createSelect();
    if($term= Yii::$app->getRequest()->get('term')){
         $query->setQuery($term);
    }
    return $this->render('search', ['query' => $query]);
}
```

and then in your view:
```php
$d = new SolrDataProvider([
    'query' => $query,
    'modelClass' => 'common\models\SolrResult',
]);

echo Html::beginForm();
echo Html::inputField('term', Yii::$app->getRequest()->get('term'), ['class' => 'form-control']);
echo Html::submitButton('Search');
echo Html::endForm();

echo yii\widgets\ListView::widget([
    'dataProvider' => $d,
    'showOnEmpty' => false,
    'emptyText' => '',
    'itemView' => '//site/_solrResult',
    'itemOptions' => ['class' => 'item-bordered'],
    'layout' => '<div class="summary-row hidden-print clearfix">{summary}<ul class="list-sorter"><li><b>Sort By:</b></li><li>{sorter}</li></ul></div>{items}{pager}',
]);
```

You will need to replace `common\models\SolrResult` with your own and the view `_solrResult` but that shows basically how to do it.

**Comment by Sammaye** [comment]
> Are they custom made ? Can you provide examples of code inside, what do we need there ?

My bad, I wrote the readme when it was still in my personal app structure.

**Comment by Sammaye** [comment]
The SolrResult is nothing more than a object creater, i.e.:

```php
class SolrResult extends Model implements SolrDocumentInterface
{
    public static function populateFromSolr($doc)
    {
        if($doc->document_type === 'title'){
            $model = new Title() /* your own model here */;
            $model->id = Solr::int($doc->title_id);
        }
        return $model;
    }
}
```

**Comment by nenad-zivkovic** [comment]
Thank you, but you confused me with this:

    if($doc->document_type === 'title'){
            $model = new Title() /* your own model here */;
            $model->id = Solr::int($doc->title_id);
    }

    document_type === 'title' ???
    $model = new Title() /* your own model here */; What model ?
    $doc->title_id ; title_id ? where does this comes from ?

Do I have to write this if statement for every model that I want solr to search from ?

**Comment by Sammaye** [comment]
That was an example of what I did, in an app I made I had a model called `Title`.

That is the process I went through to assign Solr variables to the `Title` model. It just shows you an example of what is required, you can code it anyway you want so long as you return a model and not a random array

**Comment by nenad-zivkovic** [comment]
Oh I understand now. Thank you a lot, I can't wait to try this extension and solr.

Cheers mate ;)

**Comment by Sammaye** [comment]
Awesome and NP :)
