### ISSUE TITLE
Hi Sam  - Need help in integrate SOLR in YII2 

### ISSUE THREAD

**Issue by anurupborah2001** [Sammaye/yii2-solr#4]
Hi Sam,
             I installed SOLR in localhost and below URL is working  : 
http://localhost:8983/solr/demo/select?q=*:*&wt=json&indent=true&defType=edismax&qf=solr_demo_articletitle^20.0 OR solr_articledesc^0.3

The above URL seems to work and its displays the results.

But when I try to use the query parameter in YII2 solr it displays 0 result.
The below are the code that i executed in YII2 : 

$query = Yii::$app->solr->createSelect();
 $query->setQuery('q=*:*&wt=json&indent=true&defType=edismax&qf=solr_demo_articletitle^20.0 OR solr_articledesc^0.3');
$result = Yii::$app->solr->select($query);
 var_dump($result->getNumFound());

It returns int(0);

The below is the YII2 configuration for SOLR : 

'solr' => array(
                                    'class' => 'sammaye\solr\Client',
                                    'options' => array(
                                        'endpoint' => array(
                                            'solr1' => array(
                                                'host' => 'localhost',
                                                'port' => '8983',//8983
                                                'path' => '/solr/demo'
                                            )
                                        )
                                    )
                                ),

Kindly assist where I am getting wrong in the above code.
 
Thanks

**Comment by Sammaye** [comment]
The problem is that Solarium breaks your query out to different sections, i.e. you edismax is broken out as such: http://wiki.solarium-project.org/index.php/V3:EDisMax_component

So you need to work around Solarium's OOP interface on this one.

**Comment by anurupborah2001** [comment]
Hi Sam,
             Thanks a lot for your reply.
The below query made it work :
$query = Yii::$app->solr->createSelect();
$edismax = $query->getEDisMax();
$query->setQuery('solr_articledesc:newsarticle');
$result = Yii::$app->solr->select($query);
var_dump($result);

it returns one record.

Thanks alot
