### ISSUE TITLE
Connection object used but not defined?

### ISSUE THREAD

**Issue by eborned** [Sammaye/yii2-solr#6]
In the SolrDataProvider, a reference to Connection is used. But the class itself does not exists and is not imported.

**Comment by Sammaye** [comment]
Indeed this must have been when I considered there would be such a class, needs fixing

**Comment by Sammaye** [comment]
https://github.com/Sammaye/yii2-solr/commit/fb2394987d3a2a919347d22397f6ce657d47d2c7
