### ISSUE TITLE
Error: Cannot find ModelClass

### ISSUE THREAD

**Issue by mcki0127** [Sammaye/yii2-solr#8]
Hi Sam or anyone else that has gotten this to work.
First, thanks for making this code available!  
I am running into an error when I try to pass the data provider to a ListView widget.  It is giving me the error: Class 'SolrResult' not found.
I've outlined the problem in more detail on the Yii forum: [http://www.yiiframework.com/forum/index.php/topic/70149-sammayeyii2-solr/](http://www.yiiframework.com/forum/index.php/topic/70149-sammayeyii2-solr/).  
Any thoughts about what is causing this?  Thanks in advance!

**Comment by Sammaye** [comment]
replied to on forums
